### ISSUE TITLE
Failed to load the atom-bugs-nodejs package

### ISSUE THREAD

**Issue by javaqiang** [atom-bugs/atom-bugs-nodejs#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [atom-bugs-nodejs](https://github.com/atom-bugs/atom-bugs-nodejs) package 0.5.3

### Stack Trace

Failed to load the atom-bugs-nodejs package

```
At Cannot find module 'atom-bugs-chrome-debugger/lib/plugin'

Error: Cannot find module 'atom-bugs-chrome-debugger/lib/plugin'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.15.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-bugs-nodejs/lib/plugin/node-plugin.js:48:16)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-bugs-nodejs/lib/main.js:3:21)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-bugs 1.2.16 
atom-bugs-nodejs 0.5.3 
atom-bugs-syntax 1.9.3 
atom-bugs-ui 1.8.4 
goto-definition 1.3.1 
```

**Comment by willyelm** [comment]
Please try latest version, I have fixed the issue.
